require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TreesController do

  # This should return the minimal set of attributes required to create a valid
  # Tree. As you add validations to Tree, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TreesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all trees as @trees" do
      tree = Tree.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trees).should eq([tree])
    end
  end

  describe "GET show" do
    it "assigns the requested tree as @tree" do
      tree = Tree.create! valid_attributes
      get :show, {:id => tree.to_param}, valid_session
      assigns(:tree).should eq(tree)
    end
  end

  describe "GET new" do
    it "assigns a new tree as @tree" do
      get :new, {}, valid_session
      assigns(:tree).should be_a_new(Tree)
    end
  end

  describe "GET edit" do
    it "assigns the requested tree as @tree" do
      tree = Tree.create! valid_attributes
      get :edit, {:id => tree.to_param}, valid_session
      assigns(:tree).should eq(tree)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tree" do
        expect {
          post :create, {:tree => valid_attributes}, valid_session
        }.to change(Tree, :count).by(1)
      end

      it "assigns a newly created tree as @tree" do
        post :create, {:tree => valid_attributes}, valid_session
        assigns(:tree).should be_a(Tree)
        assigns(:tree).should be_persisted
      end

      it "redirects to the created tree" do
        post :create, {:tree => valid_attributes}, valid_session
        response.should redirect_to(Tree.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tree as @tree" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tree.any_instance.stub(:save).and_return(false)
        post :create, {:tree => { "type" => "invalid value" }}, valid_session
        assigns(:tree).should be_a_new(Tree)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tree.any_instance.stub(:save).and_return(false)
        post :create, {:tree => { "type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tree" do
        tree = Tree.create! valid_attributes
        # Assuming there are no other trees in the database, this
        # specifies that the Tree created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tree.any_instance.should_receive(:update).with({ "type" => "" })
        put :update, {:id => tree.to_param, :tree => { "type" => "" }}, valid_session
      end

      it "assigns the requested tree as @tree" do
        tree = Tree.create! valid_attributes
        put :update, {:id => tree.to_param, :tree => valid_attributes}, valid_session
        assigns(:tree).should eq(tree)
      end

      it "redirects to the tree" do
        tree = Tree.create! valid_attributes
        put :update, {:id => tree.to_param, :tree => valid_attributes}, valid_session
        response.should redirect_to(tree)
      end
    end

    describe "with invalid params" do
      it "assigns the tree as @tree" do
        tree = Tree.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tree.any_instance.stub(:save).and_return(false)
        put :update, {:id => tree.to_param, :tree => { "type" => "invalid value" }}, valid_session
        assigns(:tree).should eq(tree)
      end

      it "re-renders the 'edit' template" do
        tree = Tree.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tree.any_instance.stub(:save).and_return(false)
        put :update, {:id => tree.to_param, :tree => { "type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tree" do
      tree = Tree.create! valid_attributes
      expect {
        delete :destroy, {:id => tree.to_param}, valid_session
      }.to change(Tree, :count).by(-1)
    end

    it "redirects to the trees list" do
      tree = Tree.create! valid_attributes
      delete :destroy, {:id => tree.to_param}, valid_session
      response.should redirect_to(trees_url)
    end
  end

end
